In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
file_path = 'titanic.csv'

print(f"--- 2. Load & EDA: {file_path} ---")
df = pd.read_csv(file_path)

print("Data 5 baris pertama (head):")
print(df.head())
print("\n")

print("Info Tipe Data & Cek Awal Missing Value (info):")
df.info()
print("\n")

print("Statistik Deskriptif (describe):")
print(df.describe())
print("\n")


print("--- 3. Deteksi Missing Values ---")
missing_values = df.isnull().sum()

print("Jumlah missing values per kolom (sebelum imputasi):")
print(missing_values[missing_values > 0])
print("\n")


print("--- 4. Imputasi Missing Values ---")

median_age = df['age'].median()
print(f"Nilai median 'age' yang akan digunakan: {median_age}")

df['age'] = df['age'].fillna(median_age)

print("Imputasi kolom 'age' selesai.\n")


print("--- Verifikasi Hasil Imputasi ---")
print("Cek ulang missing values setelah 'age' diisi:")
final_missing = df.isnull().sum()

print(final_missing[final_missing > 0])
print("\n")

print(f"Jumlah missing value di 'age' sekarang: {df['age'].isnull().sum()}")


output_filename = 'titanic_cleaned.csv'
df.to_csv(output_filename, index=False)
print(f"Data bersih telah disimpan ke: {output_filename}")

--- 2. Load & EDA: titanic.csv ---
Data 5 baris pertama (head):
   survived  pclass                                               name     sex   age     fare  sibsp  parch
0         0       3                            Braund, Mr. Owen Harris    male  22.0   7.2500      1      0
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833      1      0
2         1       3                             Heikkinen, Miss. Laina  female  26.0   7.9250      0      0
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000      1      0
4         0       3                           Allen, Mr. William Henry    male  35.0   8.0500      0      0


Info Tipe Data & Cek Awal Missing Value (info):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  714 non-null    int64
 1   pclass    714 non-null    int64
 2   name      714 non-null    object
 3   sex       714 non-null    object
 4   age       713 non-null    float64
 5   fare      714 non-null    float64
 6   sibsp     714 non-null    int64
 7   parch     714 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 44.8+ KB


Statistik Deskriptif (describe):
         survived      pclass         age        fare       sibsp       parch
count  714.000000  714.000000  713.000000  714.000000  714.000000  714.000000
mean     0.406162    2.236695   29.660827   34.694514    0.512605    0.431373
std      0.491460    0.838250   14.500593   52.918930    0.929783    0.853289
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.000000    8.050000    0.000000    0.000000
50%      0.000000    2.000000   28.000000   15.741700    0.000000    0.000000
75%      1.000000    3.000000   38.000000   33.375000    1.000000    1.000000
max      1.000000    3.000000   80.000000  512.329200    5.000000    6.000000


--- 3. Deteksi Missing Values ---
Jumlah missing values per kolom (sebelum imputasi):
age    1
dtype: int64


--- 4. Imputasi Missing Values ---
Nilai median 'age' yang akan digunakan: 28.0
Imputasi kolom 'age' selesai.

--- Verifikasi Hasil Imputasi ---
Cek ulang missing values setelah 'age' diisi:
Series([], dtype: int64)


Jumlah missing value di 'age' sekarang: 0
Data bersih telah disimpan ke: titanic_cleaned.csv